// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRxUDCI7a66Hyt06TKL6lHLWDesEnG06M',
    appId: '1:867070227950:android:25fff798caf304daffcaff',
    messagingSenderId: '867070227950',
    projectId: 'achiever-18331',
    storageBucket: 'achiever-18331.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUhCpv-Ub7dSv_8JrjmbBVkCM3neQyF6w',
    appId: '1:867070227950:ios:45b5ae487162937bffcaff',
    messagingSenderId: '867070227950',
    projectId: 'achiever-18331',
    storageBucket: 'achiever-18331.firebasestorage.app',
    androidClientId: '867070227950-4mmeq7mbm0duig1bjpov3js5hjvue60d.apps.googleusercontent.com',
    iosClientId: '867070227950-8390sgcebe8pn4pd2am7mg0d4dpibeuv.apps.googleusercontent.com',
    iosBundleId: 'com.achiever.achiever',
  );

}